config/routes.rb
Rails.application.routes.draw do

root to: 'pages#home'

 resources :events, only: [:new, :create] do
  resources :users, only: [:new, :create]
end

  resources :users, only: [] do
    resources :uptimes, only: [:new, :create]
  end

  resources :events, only: [:show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "events/:id/create_orga", to: "users#create_orga", as: "create_orga"


  get "events/:id/calendar_show", to: "events#calendar_show", as: "calendar"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :users

  attr_writer :current_step

  validates :start_time, presence: true

  def start_event
    self.start_time.split(',').map(&:to_date)
  end

  def range_event
    date_array = self.start_time.split(',').map(&:to_date)
    return date_array.min..date_array.max
  end

  def date_pick
    dates = []
    self.start_time.each do |date|
      dates << date
    end
  end

  def number_user
    self.users.count
  end

  def participants
    participants = Hash.new(0)
    self.users.each do |user|
      self.start_event.each do |item|
        unless user
          participants[item] = 0
        else
          user.date_user.include?(item) ? participants[item] += 1 : participants[item] += 0
        end
      end
    end
    participants
  end

  def define_date_for_user
    dates_event = self.participants
    dates = []
    dates_event.each do |date, number_participant|
      if self.number_user == 2
        if [true, true, false].sample
          dates << date
        end

      elsif number_participant != (self.number_user - 1)
        if [true, true, false].sample
          dates << date
        end
      end
    end
    dates.join(', ')
  end

# form in several steps
  def steps
    %w[name time]
  end

  def current_step
    @current_step || steps.first
  end

  def next_step
    self.current_step = steps[steps.index(current_step) + 1]
  end

  def previous_step
    self.current_step = steps[steps.index(current_step) - 1]
  end

  def first_step?
    self.current_step == steps.first
  end

  def last_step?
    self.current_step == steps.last
  end
end

app/models/uptime.rb
class Uptime < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :event
  has_many :uptimes

  def start_event
    self.start_time.split(',').map(&:to_date)
  end

  def date_user
    dates_user = []
    self.uptimes.each do |dates|
      dates_user = dates.start_time.split(',').map(&:to_date)
    end
    dates_user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def new
    @event = Event.new
    session[:event_params] = {}
  end

  def create
    session[:event_params].deep_merge!(event_params) if event_params
    @event = Event.new(session[:event_params])

    @event.current_step = session["current_step"]
    @dates = params[:event][:start_time]

    if params["back_button"]
      @event.previous_step
    elsif @event.last_step?
      @event.save
    else
      @event.next_step
    end

    session["current_step"] = @event.current_step

    if @event.save
      flash[:notice] = 'event saved successfully'
      redirect_to create_orga_path(@event)
    else
      render "new"
      flash[:notice] = 'event was not saved yet.'
    end
  end

  def show
    @event = Event.find(params[:id])
    @users = User.where("event_id = '#{@event.id}'")
  end

  def calendar_show
    @event = Event.find(params[:id])
    @users = User.where("event_id = '#{@event.id}'")
  end

  private

  def event_params
    params.require(:event).permit(:name, :place, :note, :start_time, :ending_at)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @thesis = Event.find_by(name: 'Thesis soutenance')
    @wedding = Event.find_by(name: 'Wedding')
    @meeting = Event.find_by(name: 'Meeting')
  end
end

app/controllers/uptimes_controller.rb
class UptimesController < ApplicationController

  def new
    @uptime = Uptime.new
    @user = User.find(params[:user_id])
    @event = Event.where("id = '#{@user.event_id}'")
  end

  def create
    @user = User.find(params[:user_id])
    @event = Event.find(@user.event_id)

    if @user.role == "Organisator"
      @uptime = Uptime.create(start_time: @event.start_time)
      @uptime.start_time = @event.start_time
    else
      @uptime = Uptime.new(uptime_params)
    end

    @uptime.user = @user

    if @uptime.save
      redirect_to event_path(@event)
    end
  end

  private

  def uptime_params
    params.require(:uptime).permit(:start_time)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
    @user = User.new
    @user.event = @event
  end

  def create
    @user = User.new
    @event = Event.find(params[:event_id])
    @user = User.new(user_params)
    @user.event = @event
    @user.save

    if @user.save
      define_uptime(@user)
    end
  end

  def create_orga
    @event = Event.find(params[:id])
    @user = User.new
    @user.event = @event
    @user = User.new(user_params_orga)
    @user.role = "Organisator"

    if @user.save
      define_uptime(@user)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :role)
  end

  def user_params_orga
    params.permit(:user).permit(:name, :role)
  end

  def uptime_params
    params.permit(:start_time, :user)
  end

  # def define_uptime(user)
  #   if user.role == "Organisator"
  #     @uptime = Uptime.create!(start_time: @event.start_time, user: user)
  #     @uptime.start_time = @event.start_time
  #   else
  #     @uptime = Uptime.new(uptime_params)
  #   end
  # end

  def define_uptime(user)
    if user.role == "Organisator"
      @uptime = Uptime.create!(start_time: @event.start_time, user: user)
      @uptime.start_time = @event.start_time
      if @uptime.save
        redirect_to event_path(@event)
      end
    else
      ### uptime for invite people
      @event.start_event.empty? ? user_date = "" : user_date = @event.define_date_for_user
      @uptime = Uptime.create!(start_time: user_date, user: user)
      if @uptime.save
        redirect_to event_path(@event)
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/uptimes_helper.rb
module UptimesHelper
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/events/_calendar.html.erb
  <div class="table-container scroller">
      <table class="doodles-calendar">
        <colgroup>
          <col span="1" class = "wide">
        </colgroup>
        <tr>
          <!-- first Row with Dates -->
          <th></th>
          <% (@event.start_event).each do |date| %>
            <th>
              <div class="date-cells">
                <p> <%= date.strftime("%B") %></p>
                <span> <%= date.strftime("%d") %> </span>
                <p> <%= date.strftime('%a') %>.</p>
              </div>
            </th>
          <% end %>
        </tr>
        <tr>
          <td>
            <div class = "user-cell">
              <p> All day </p>
            </div>
          </td>
          <% @event.participants.each do |date, number| %>
            <td class="part-number-calendar">
              <div class= <%= number == @users.count ? "cal-here" : "cal-nothere"  %> >
                <% if number == @users.count %>
                  <i class="fas fa-check" style="color:#169E1E;font-weight: bold;font-size: 20px"></i>
                <% else %>
                  <i class="fas fa-times" style="color:red;font-weight: bold;font-size: 20px"></i>
                <% end %>
                <p> <i class="fas fa-check"></i> <%= number %></p>
              </div>
            </td>
          <% end %>
        </tr>
      </table>
    </div>
    <div class="edt-info edt-diplay ">
      <div>
        <%= link_to "Invite an user", new_event_user_path(@event), class: "buttonval"  %>
      </div>
      <div>
        <%= link_to "Home", root_path, class: "back"  %>
      </div>
    </div>
  </div>

app/views/events/_name_step.html.erb
<div class="header">
  <p> Step 1 to 3</p>
  <h1> What's the occasion ?</h1>
</div>

  <div class="form-container">
    <i class="fas fa-grip-lines" style="color:gray"></i> <%= f.input :name, placeholder: 'Enter title', label: false %>
  </div>
  <div class="form-container">
    <i class="fas fa-map-marker" style="color:gray"></i> <%= f.input :place, placeholder: 'Add location', label: false %>
  </div>
  <div class="form-container-note">
    <i class="fas fa-align-justify" style="color:gray"></i> <%= f.input :note, placeholder: 'Add note', label: false %>
  </div>

app/views/events/_table.html.erb
<div class="table-container scroller">
  <table class="doodles">
    <colgroup>
      <col span="1" class = "wide">
    </colgroup>
    <tr>
      <!-- first Row with Dates -->
      <th></th>
      <% (@event.start_event).each do |date| %>
        <th>
          <div class="date-cells">
            <p> <%= date.strftime("%B") %></p>
            <span> <%= date.strftime("%d") %> </span>
            <p> <%= date.strftime('%a') %>.</p>
          </div>
        </th>
      <% end %>
    </tr>
    <tr>
      <td>
        <div class = "user-cell">
          <p> <%= pluralize @event.users.count, "participant"  %></p>
        </div>
      </td>
      <% @event.participants.each do |date, number| %>
        <td class="part-number">
          <p> <i class="fas fa-check"></i> <%= number %></p>
        </td>
      <% end %>
    </tr>
    <% unless @users.empty? %>
      <% @users.each do |user| %>
      <tr>
        <td>
          <div class = "user-cell">
            <i class="fas fa-user"></i> <p><%= user.name.capitalize() %></p>
          </div>
        </td>
          <% (@event.start_event).each do |item| %>
            <% if user.date_user.include?(item) %>
              <td class="here"> <i class="fas fa-check"></i> </td>
            <% else %>
              <td class="nothere"> </td>
            <% end %>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>

app/views/events/_time_step.html.erb
<div class="header">
  <p> Step 2 to 3</p>
  <h1> What are the options?</h1>
</div>

<div class="form-container">
  <%= f.input :start_time, as: :date, html5: true, input_html: { id: "start_date" }, label: false, error: 'Please specify a date.' %>
</div>

app/views/events/calendar_show.html.erb
<div class = "edt">
  <h1> <%= @event.name.capitalize() %> </h1>
  <div class = "edt-header">
    <p> by <%=@event.users.first.name %> </p> <p> <i class="fas fa-circle" style="color:gray;font-size:10px"> </span> </i></p>
    <p> <%= ((Time.now - @event.created_at )/6000).round() %> mins ago<p> <i class="fas fa-circle" style="color:gray;font-size:10px"> </span> </i></p>
    <p> <%= "Print" %></p>
  </div>
  <div class = "edt-info">
    <div class="edt-info-container">
      <p> <i class="fas fa-map-marker" style="color:gray"></i> </p> <p> <%= @event.place %></p>
    </div>

   <div class="edt-info-container">
      <p> <i class="fas fa-align-justify" style="color:gray"></i> </p>
      <div class="limit">
        <p> <%= @event.note %> </p>
      </div>
    </div>
  </div>

  <div class="tabs">
    <%= link_to "Table", event_path(@event), class: "link" %>
    <%= link_to "Calendar", calendar_path(@event), class: "blue_link" %>
  </div>
    <%= render "calendar" %>
</div>

app/views/events/new.html.erb
<div class="size-screen">
  <div class="page-content ">
    <%= simple_form_for @event do |f| %>
      <div class="form">
          <%= render "#{@event.current_step}_step", :f => f  %>
        <div class = "sub-button-form">
          <%= f.submit "back", class: 'back', label: false, :name => "back_button" unless @event.first_step?  %>
          <%= f.submit "Continue", class: 'button',
          id: "buttonvalform",
          disabled: @event.first_step? %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<div class="container">
  <div class = "edt">
    <h1> <%= @event.name.capitalize() %> </h1>
    <div class = "edt-header">
      <p> by <%=@event.users.first.name %> </p> <p> <i class="fas fa-circle" style="color:gray;font-size:10px"> </span> </i></p>
      <p> <%= ((Time.now - @event.created_at )/6000).round() %> mins ago<p> <i class="fas fa-circle" style="color:gray;font-size:10px"> </span> </i></p>
      <p> <%= "Print" %></p>
    </div>
    <div class = "edt-info">
      <div class="edt-info-container">
        <p> <i class="fas fa-map-marker" style="color:gray"></i> </p> <p> <%= @event.place %></p>
      </div>

     <div class="edt-info-container">
        <p> <i class="fas fa-align-justify" style="color:gray"></i> </p>
        <div class="limit">
          <p> <%= @event.note %> </p>
        </div>
      </div>
    </div>

    <div class="tabs">
      <%= link_to "Table", event_path(@event), class: "blue_link" %>
      <%= link_to "Calendar", calendar_path(@event), class: "link" %>
    </div>
    <%= render "table" %>
    <div class="edt-info edt-diplay ">
      <div>
        <%= link_to "Invite an user", new_event_user_path(@event), class: "buttonval"  %>
      </div>
      <div>
        <%= link_to "Home", root_path, class: "back"  %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CursedDoodles</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://unpkg.com/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= favicon_link_tag asset_path('favicon.jpg') %>

    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>"/>

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="font">
    <div class="intro">
      <h1> Cursed planner </h1>
      <div class="intro-message ">
        <h2> We offer you an unique planning simulation experience : </h2>
        <p class = "whitebutton margin">  <%= link_to "Try now!", new_event_path %> </p>
      </div>
    </div>
  </div>

  <div class="kpi-section">
    <div>
      <div class="text-align">
        <h2></h2>
      </div>
    </div>
    <div class="flex_response kpi">
      <div class="metric_box">
        <div>
          <span class="kpi-value" id="user">6600</span>
        </div>
        <div>
          <p class="kpi-title">User</p>
        </div>
      </div>
      <div class="metric_box">
        <div>
          <span class="kpi-value">26</span>
        </div>
        <div>
          <p class="kpi-title">Country</p>
        </div>
      </div>
      <div class="metric_box">
        <div>
          <span class="kpi-value">4</span>
        </div>
        <div>
          <p class="kpi-title">Year activity</p>
        </div>
      </div>
      <div class="metric_box">
        <div>
          <span class="kpi-value">99</span>
          <span>%</span>
        </div>
        <div>
          <p class="kpi-title">Satisfaction</p>
        </div>
      </div>

    </div>
    <p class="faker">These numbers are totally fake</p>
    <hr>
  </div>

  <div class="text-intro invisible">
    <h2> You need to plan and event gathering a lot of more and less busy people and you dont know how to find a date
    for everybody ? </h2>
    <h2> That great !!</h2>
    <h2>  Well, do you need a date for : </h2>
  </div>

  <div class="sub invisible">
    <div class="container">
      <div class="info">
        <div class="picture">
          <%= link_to event_path(@thesis) do %>
            <%= image_tag("student.jpg", alt: 'Logo')%>
          <% end %>
          <%= link_to event_path(@thesis) do %>
            <%= image_tag("thesis_schedule.jpg", alt: 'Logo') %>
          <% end %>
        </div>
        <div class="rigth-t">
          <h3> Your <span>thesis soutenance</span> ?</h3>
          <p> You probably need to gather people around the country with very specific academic background ? </p>
          <p class="testimony"> "So accurate! We took 6 extra months to gather everyone for my thesis! But I am finaly doctor now!"</p>
          <p class="author">Emilie</p>
        </div>
      </div>
    </div>
  </div>

  <div class="sub invisible">
    <div class="container">
      <div class="info">
        <div class="left-t">
          <h3> Your <span>wedding</span> ?</h3>
          <p> You might want several close friends and distant family members to be attending to this special event </p>
          <p class="testimony"> "Amazing prediction! We never find a date where everybody were avalaible for my weeding! I am still single but now I hate my family even more!"</p>
          <p class="author">Marie</p>
        </div>
        <div class="picture">
         <%= link_to event_path(@wedding) do %>
            <%= image_tag("wedding.jpg", alt: 'Logo')%>
          <% end %>
          <%= link_to event_path(@wedding) do %>
            <%= image_tag("wedding_schedule.jpg", alt: 'Logo')%>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <div class="sub invisible">
    <div class="container">
      <div class="info">
        <div class="picture">
         <%= link_to event_path(@meeting) do %>
            <%= image_tag("employe.jpg", alt: 'Logo')%>
          <% end %>
          <%= link_to event_path(@meeting) do %>
            <%= image_tag("boss_schedule.jpg", alt: 'Logo')%>
          <% end %>
        </div>
        <div class="rigth-t">
          <h3> This important <span>meeting with your boss</span> ?</h3>
          <p> You know the one who absolutely needs your boss, your boss' boss and other very busy people </p>
          <p class="testimony"> "Great service! I never succeeded to gather everyone for my promotion. Actualy they fired me in the meantime..."</p>
          <p class="author">Derek</p>
        </div>
      </div>
    </div>
  </div>

  <div class="text-intro invisible">
    <h2> Dont worry, we know what you're going through. <br>
  We can help you to predict what gonna happen ...
    <h1 class = "blackbutton margin">  <%= link_to "Try now!", new_event_path %> </h1>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-category footer-nav">
    <%= link_to "/" do %>
      <p>About</p>
    <% end %>
    <%= link_to 'https://github.com/hbiom/cursed_doodles' do %>
      <p>Github</p>
    <% end %>
    <%= link_to "/" do %>
      <p>Privacy</p>
    <% end %>
    <%= link_to "/" do %>
      <p>FAQ</p>
    <% end %>
  </div>

  <div class="footer-category footer-social">
<!--     <%= link_to "/" do %>
      <p> icon </p>
    <% end %>
    <%= link_to "/" do %>
      <p> icon </p>
    <% end %>
    <%= link_to "/" do %>
      <p> icon </p>
    <% end %>
    <%= link_to "/" do %>
      <p> icon </p>
    <% end %> -->
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-md navbar-light navbar-lewagon">

  <div class="navbar-brand">
    <%= link_to "/" do %>
      <h2 id="logo">Cursed Planner </h2>
    <% end %>

  </div>

</div>

app/views/uptimes/_form.html.erb
<div class="size-screen">

  <%= simple_form_for ([@user,@uptime]) do |f| %>
    <div class="form">
      <div class="form-container">
        <%= f.input :start_time, as: :date, html5: true, input_html: { id: "start_date_user" } %>
      </div>

      <div class="sub-button-form">
        <%= f.submit "continue", class: 'button' %>
      </div>
    </div>
  <% end %>

</div>

app/views/uptimes/new.html.erb
<div class="size-screen">
  <div class="page-content ">
    <h1>Uptimes#new</h1>
    <p>Find me in app/views/uptimes/new.html.erb</p>
   <%= render "form", uptime: @uptime %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="header">
  <p> Step 3 to 3</p>
  <h1> Tell your participants who you are ? </h1>
</div>
<%= simple_form_for [@event, @user] do |f| %>
  <div class="form">
    <div class="form-container">
      <i class="fas fa-user" style="color:gray"></i><%= f.input :name, placeholder: 'Enter name', label: false %>
    </div>
    <div class="form-container">
      <i class="fas fa-smile" style="color:gray"></i><%= f.input :role, placeholder: 'Enter role', label: false %>
    </div>
    <div class = "sub-button-form">
      <%= f.button :submit, class: @event.first_step? ? 'button' : 'buttonval',
        id: "buttonvalformuser",
        disabled: @event.first_step? %>
    </div>
  </div>
<% end %>

app/views/users/_formuser.html.erb
<div class="header">
  <p></p>
  <h1> Who are your participants ? </h1>
</div>
<%= simple_form_for [@event, @user] do |f| %>
  <div class="form">
    <div class="form-container">
      <%= f.input :name %>
    </div>
    <div class="form-container">
      <%= f.input :role %>
    </div>
    <div class = "sub-button-form">
      <%= f.button :submit, class: 'button', id:"buttonvalformuser" %>
    </div>
  </div>
<% end %>

app/views/users/create_orga.html.erb
<div class="size-screen">
  <div class="page-content ">
    <%= render "form", event: @event %>
  </div>
</div>

app/views/users/new.html.erb
<div class="size-screen">
  <div class="page-content ">
    <%= render "formuser", user: @user %>
  </div>
</div>